[project]
name = "ship-guard"
version = "0.1.0"
description = "A web application for managing and predicting delivery performance in logistics, powered by ML models trained on the Olist Brazilian E-Commerce dataset."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
]

[tool.uv.workspace]
members = ["backend"]

[tool.typos.files]
extend-exclude = [
    "img/",
    "uv.lock",
    "bun.lock",
]

[tool.typos.default]
extend-ignore-re = [
    # GitHub usernames in @mentions
    "@[a-zA-Z0-9](?:-?[a-zA-Z0-9])*",
    # Name of the package in the PR title
    "Bump certifi ",
]

[tool.typos.default.extend-identifiers]
alls = "alls"

