"""add product weight_g

Revision ID: 1a82b365f2a1
Revises: 65456c8a379a
Create Date: 2026-08-23 20:26:22.479748

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1a82b365f2a1'
down_revision = '65456c8a379a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('weight_g', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'weight_g')
    # ### end Alembic commands ###
