"""add order payments table and purchase timestamp

Revision ID: 65456c8a379a
Revises: 96600252b983
Create Date: 2026-08-23 12:35:43.321223

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '65456c8a379a'
down_revision = '96600252b983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderpayment',
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('payment_sequential', sa.Integer(), nullable=False),
    sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('payment_installments', sa.Integer(), nullable=False),
    sa.Column('payment_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('order_id', 'payment_sequential')
    )
    op.add_column('order', sa.Column('order_purchase_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_purchase_timestamp')
    op.drop_table('orderpayment')
    # ### end Alembic commands ###
