"""add order lookup tables

Revision ID: a113bc3b92e6
Revises: 4a5394cf80a2
Create Date: 2026-08-22 23:07:03.549377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a113bc3b92e6'
down_revision = '4a5394cf80a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('customer_city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('customer_state', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('customer_zip_code_prefix', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('orderitem',
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('seller_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.PrimaryKeyConstraint('order_id', 'order_item_id')
    )
    op.create_index(op.f('ix_orderitem_product_id'), 'orderitem', ['product_id'], unique=False)
    op.create_index(op.f('ix_orderitem_seller_id'), 'orderitem', ['seller_id'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('category_name_english', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('seller',
    sa.Column('seller_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('seller_city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('seller_state', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.add_column('order', sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_index(op.f('ix_order_customer_id'), 'order', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_customer_id'), table_name='order')
    op.drop_column('order', 'customer_id')
    op.drop_table('seller')
    op.drop_table('product')
    op.drop_index(op.f('ix_orderitem_seller_id'), table_name='orderitem')
    op.drop_index(op.f('ix_orderitem_product_id'), table_name='orderitem')
    op.drop_table('orderitem')
    op.drop_table('customer')
    # ### end Alembic commands ###
